name: OData-Temporal
url: https://docs.oasis-open.org/odata/odata-temporal-ext/v4.0/odata-temporal-ext-v4.0.html
pagetitle: OData Extension for Temporal Data Version 4.0
subtitle: Committee Specification Draft 04
filename: odata-temporal-ext-v4.0-csd04
stage: csd04
previousStage: cs01
pubdate: 25 January 2022
pubdateISO: '2022-01-25'
copyright: © OASIS Open 2022
additionalArtifacts:
  - repo: odata-vocabularies
    path: vocabularies/Org.OData.Temporal.V1.json
  - repo: odata-vocabularies
    path: vocabularies/Org.OData.Temporal.V1.xml
  - repo: odata-abnf
    path: abnf/odata-abnf-construction-rules.txt
  - repo: odata-abnf
    path: abnf/odata-abnf-testcases.yaml
  - repo: odata-abnf
    path: abnf/odata-temporal-abnf.txt
  - repo: odata-abnf
    path: abnf/odata-temporal-testcases.yaml
  - repo: odata-abnf
    path: syntax-diagram
OData-ABNF: https://oasis-tcs.github.io/odata-abnf/odata-abnf-diagrams.html
OData-VocCore: https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Core.V1.md
OData-VocCap: https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md
OData-VocAggr: https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Aggregation.V1.md
description:
  This specification defines how to represent and interact with time-dependent data using the Open Data Protocol (OData).
