name: OData-JSON
url: https://docs.oasis-open.org/odata/odata-json-format/v4.02/odata-json-format-v4.02.html
pagetitle: OData JSON Format Version 4.02
subtitle: Committee Specification Draft 02
filename: odata-json-format-v4.02-csd02
stage: csd02
previousStage: csd01
pubdate: 28 February 2024
pubdateISO: '2024-02-28'
copyright: © OASIS Open 2024
additionalArtifacts:
  - repo: odata-abnf
    path: abnf/odata-abnf-construction-rules.txt
    branch: v4.02-release-candidate
  - repo: odata-abnf
    path: abnf/odata-abnf-testcases.yaml
    branch: v4.02-release-candidate
  - repo: odata-abnf
    path: syntax-diagram
    branch: v4.02-release-candidate
OData-ABNF: https://oasis-tcs.github.io/odata-abnf/odata-abnf-diagrams.html
OData-VocCore: https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Core.V1.md
OData-VocCap: https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md
OData-VocAggr: https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Aggregation.V1.md
description: >
  The Open Data Protocol (OData) for representing and interacting with structured
  content is comprised of a set of specifications. The core specification for the
  protocol is in OData Version 4.02 Part 1: Protocol.
  This document extends the core specification by defining representations for
  OData requests and responses using a JSON format.
